### ISSUE TITLE
你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激

### ISSUE THREAD

**Issue by zaijian001** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#1]
![image](https://user-images.githubusercontent.com/77659578/143769451-d408b907-6a10-4e68-8558-f835594eea44.png)

**Comment by Aureliano90** [comment]
不需要引号。

**Comment by zaijian001** [comment]
> 

可以了，可否留个交流方式，这个不能私信你

**Comment by Aureliano90** [comment]
@aureliano_law

**Comment by jackandres** [comment]
你好，用了你的最新更新的代码，但是有个问题，就是目前只有资金费数据可以查询到，其他的几个都报错 ，能帮忙看一下吗
![微信图片_20220113190739](https://user-images.githubusercontent.com/35865845/149322510-07c41452-b48e-4223-8ef8-d08495ce91a7.png)
![微信图片_20220113190744](https://user-images.githubusercontent.com/35865845/149322530-b3d22b93-76e5-4554-a2f1-30173164cc9d.png)
![微信图片_20220113190731](https://user-images.githubusercontent.com/35865845/149322551-9d51b21b-e1ba-450d-a249-fe2f9467969e.png)
？

**Comment by zaijian001** [comment]
我也是用的别人的，对这个代码并不是很熟悉，抱歉







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aureliano90/Futures-Spot-Arbitrage-OKEx-V5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)





 
你好，用了你的最新更新的代码，但是有个问题，就是目前只有资金费数据可以查询到，其他的几个都报错 ，能帮忙看一下吗
 
 
 
 ？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
导入API Key。

**Comment by jackandres** [comment]
你好，
         我目前是导入的有API Key的，放在key.py这里面的，然后那个okex/client.py也填了有api_key的，不知道你说的导入指的是创建一个新的api.json还是其他的方法？



***@***.***
 
发件人： Aureliano
发送时间： 2022-01-14 15:23
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
导入API Key。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jackandres** [comment]
***@***.***
 
发件人： Aureliano
发送时间： 2022-01-14 15:23
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
导入API Key。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
你都没建仓，其他功能自然没用。

**Comment by jackandres** [comment]
你好，
          我前两天在有建仓的情况，执行程序也是报“未建仓”



***@***.***
 
发件人： Aureliano
发送时间： 2022-01-16 00:00
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
你都没建仓，其他功能自然没用。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
MongoDB装了？

**Comment by jackandres** [comment]
mongo是正常启动的



***@***.***
 
发件人： Aureliano
发送时间： 2022-01-16 00:04
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
MongoDB装了？
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
你说的建仓，是通过程序建仓并录入数据库？根据你提供的信息，数据库里没有记录。

**Comment by jackandres** [comment]
什么意思?根据我的信息，数据库里没有信息是什么意思？我的Mongodb有验证信息的，你那边应该看不到吧？



***@***.***
 
发件人： Aureliano
发送时间： 2022-01-16 15:32
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
你说的建仓，是通过程序建仓并录入数据库？根据你提供的信息，数据库里没有记录。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
你用这个程序建仓，本地数据库就会有记录。如果数据库里都没有你的仓位信息，你还想程序返回什么？提问前麻烦先把代码看一遍。

**Comment by jackandres** [comment]
哥，
    我不是用的这个程序建的仓位，我是手动建的仓位，我是说用这个监控程序看不到我建的仓位；



***@***.***
 
发件人： Aureliano
发送时间： 2022-01-16 22:49
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
你用这个程序建仓，本地数据库就会有记录。如果数据库里都没有你的仓位信息，你还想程序返回什么？提问前麻烦先把代码看一遍。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
不是程序创建的仓位，默认是不会管的。我不会知道你哪些币要做套利，杠杆是多少。想把现有仓位纳入程序监控范围，就输入币种再选开仓，输入0 USDT，设置杠杆，再尝试监控。

**Comment by jackandres** [comment]
监控仓位的时候，报这个错，如何解决，能帮忙看一下吗，这个test需要修改成true吗？



***@***.***
 
发件人： ***@***.***
发送时间： 2022-01-16 22:54
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5; Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： Comment
主题： Re: Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
哥，
    我不是用的这个程序建的仓位，我是手动建的仓位，我是说用这个监控程序看不到我建的仓位；



***@***.***
 
发件人： Aureliano
发送时间： 2022-01-16 22:49
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
你用这个程序建仓，本地数据库就会有记录。如果数据库里都没有你的仓位信息，你还想程序返回什么？提问前麻烦先把代码看一遍。
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
看不到图。accountid=3是用来在模拟盘测试的，实盘交易换一个号码，key.py里的密码要对应。

**Comment by jackandres** [comment]
谢谢，大佬，还有一个问题想请教一下，就是我点击记录行情的时候，总是报错，是因为我的timeout设置的过小吗？

     另：大哥，能不能加你微信，给你发个红包，聊表心意，如果方便的话.
         


***@***.***
 
发件人： Aureliano
发送时间： 2022-01-17 22:35
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
看不到图。accountid=3是用来在模拟盘测试的，实盘交易换一个号码，key.py里的密码要对应。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
不知道你说的timeout是什么，10秒记录一次够了。

**Comment by jackandres** [comment]
哥，
         你那边是看不到我的图片，是吗？我这次放在附件里了，麻烦帮忙看一下，谢谢！！！！



***@***.***
 
发件人： Aureliano
发送时间： 2022-01-17 23:29
收件人： Aureliano90/Futures-Spot-Arbitrage-OKEx-V5
抄送： jackandres; Comment
主题： Re: [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5] 你好，我用了你的代码，非常棒，输入币的时候，有个问题，可以解答一下吗？不胜感激 (Issue #1)
不知道你说的timeout是什么，10秒记录一次够了。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aureliano90** [comment]
邮件里的附件GitHub是看不到的。
