### ISSUE TITLE
资金汇率 和资金费率 计算问题

### ISSUE THREAD

**Issue by LINJINTIANDE** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#10]
https://github.com/Aureliano90/Futures-Spot-Arbitrage-OKEx-V5/blob/0385a64a7b3c029d917038230e3af17d0d4e6852/src/monitor.py#L101
一个是u 一个是币 相加是不是有点问题

https://github.com/Aureliano90/Futures-Spot-Arbitrage-OKEx-V5/blob/0385a64a7b3c029d917038230e3af17d0d4e6852/src/monitor.py#L148
资金费率 是百分比而比较的是u

**Comment by Aureliano90** [comment]
手续费是百分比。

**Comment by LINJINTIANDE** [comment]
不太懂您想要说明的意思 能否说明下🙏
