### ISSUE TITLE
Parameter accountid is not passed when creating FundingRate object

### ISSUE THREAD

**Issue by Gavin2318** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#11]
In **src/menu.py, line 355**:  `fundingRate = FundingRate()` ,  I suggest to change to: `fundingRate = FundingRate(accountid)` , otherwise the `fundingRate` object with always initialized with the default `accountid, 3` , the object will always uses the test API. 

Same issue goes to: 
- src/menu.py line 27, 140
- src/monitor.py line 84
- src/record.py line 61
 
@Aureliano90

**Comment by Aureliano90** [comment]
Fixed. Thank you.
