### ISSUE TITLE
Questions on src/monitor.py

### ISSUE THREAD

**Issue by Gavin2318** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#12]
你好，在理解运行代码的时候遇到一些问题想请教下：

从**src/monitor.py**开始处的注释来看，该文件主要实现了以下三个功能：
```
# 1. 监控一个币种，如果当期资金费+预测资金费小于重新开仓成本（开仓期现差价-平仓期现差价-手续费），进行平仓。
# 2. 如果合约仓位到达下级杠杆，进行减仓。如果合约仓位到达上级杠杆，进行加仓。
# 3. 如果距离下期资金费3小时以上，（开仓期现差价-平仓期现差价-手续费）>0.2%，进行套利。
```

**Question 1** 
**1.1** 对于注释中功能1. 我的理解是， 如果资金费利润(当期资金费+下期预测资金费)小于期现差价利润(开仓期现差价-平仓期现差价-手续费)，则进行平仓直接赚取期现差价利润而舍弃资金费利润。请问这样理解是对的吗？你注释中所写的重新开仓成本就是开仓平仓是期现差价利润的意思吗？ 如果不是可否麻烦解释下？

**1.2**  代码中147行计算重新开仓成本， `cost = open_pd - close_pd + 2 * trade_fee` 这里的`trade_fee` 为什么是相加而不是相减呢？
https://github.com/Aureliano90/Futures-Spot-Arbitrage-OKEx-V5/blob/4361da6506f301f5edf03face7e73b28db72cb46/src/monitor.py#L147

**1.3** 代码143-146行中，开仓期现差价和平仓期现差价都是用该标的的过去一段时间内的统计平均加减标准差得来。为什么不能直接计算该仓位开仓时的期现差价，和当前时间点的期现差价作为平仓期现差价呢？ 
```
  assert (recent := Stat.recent_open_stat()), lang.fetch_ticker_first
  open_pd = recent['avg'] + recent['std']
  recent = Stat.recent_close_stat()
  close_pd = recent['avg'] - recent['std']
```

**Question 2** 
对于注释中功能3.我好像没有在**src/monitor.py**找到相应的代码，是该功能还没有实现吗？或者是我遗漏了哪部分代码？ 

P.S. 代码写的好好，感谢无私的分享！！

**Comment by Aureliano90** [comment]
1. 对。
2. 是负数。
3. 需要的是近期相对好可实现的开仓和平仓价格。
4. 懒得实现。
