### ISSUE TITLE
local variable 'json_res' referenced before assignment

### ISSUE THREAD

**Issue by DROID8622** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#13]
Hi, Aureliano90, I have this error if I try to monitor existing connections for example:

Monitor__await__(BTC) error
local variable 'json_res' referenced before assignment
Crypto BTC does not exist.

I have MongoDB running, may be I should configure it somehow?

Thank you

**Comment by DROID8622** [comment]
I have the same
 "local variable 'json_res' referenced before"
if I try to check "top 10 for arbitrage"

**Comment by Aureliano90** [comment]
> Hi, Aureliano90, I have this error if I try to monitor existing connections for example:
> 
> Monitor__await__(BTC) error local variable 'json_res' referenced before assignment Crypto BTC does not exist.
> 
> I have MongoDB running, may be I should configure it somehow?
> 
> Thank you

I can't reproduce the error. Are you sure you can access https://www.okx.com?

**Comment by DROID8622** [comment]
I will try to solve this soon and leave converts here, thank you again

**Comment by trkwyk** [comment]
Maybe it's related to [this](https://github.com/Aureliano90/async-okx-v5/issues/2#issue-2279515073). I can reproduce this by leaving the `.env` entries blank.

**Comment by FrostyForest** [comment]
> > Hi, Aureliano90, I have this error if I try to monitor existing connections for example:
> > Monitor__await__(BTC) error local variable 'json_res' referenced before assignment Crypto BTC does not exist.
> > I have MongoDB running, may be I should configure it somehow?
> > Thank you
> 
> I can't reproduce the error. Are you sure you can access https://www.okx.com?

in china, i can not connect to okx, how can i use proxy in your project？
