### ISSUE TITLE
谢谢，大佬，还有一个问题想请教一下，就是我点击记录行情的时候，总是报错，是因为我的timeout设置的过小吗？

### ISSUE THREAD

**Issue by jackandres** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#2]
![CatchACB1(01-17-23-40-08)_01](https://user-images.githubusercontent.com/35865845/149808887-a42cb7bc-cd6a-470d-bb6a-c85f45e2c9e8.jpg)
![CatchE82B(01-17-23-40-08)](https://user-images.githubusercontent.com/35865845/149808935-ba079614-a11f-4fd4-9763-b1d03e60eee4.jpg)

**Comment by Aureliano90** [comment]
httpx版本按requirements里的安装。

**Comment by jackandres** [comment]
![微信图片_20220121011835](https://user-images.githubusercontent.com/35865845/150389163-c558d18f-85e4-459f-bf4e-1c85b405bf6b.png)
![微信图片_20220121011843](https://user-images.githubusercontent.com/35865845/150389176-5fa9a936-6187-4772-aef3-e6763c353889.png)
开仓下单的时候为什么总提示我币种不存在？这个怎么自定义我当前的币种？

**Comment by Aureliano90** [comment]
OKEx没有YFI的合约就不能操作。加减仓需要最近行情数据确定期货升水，或者你自己指定。

**Comment by Aureliano90** [comment]
你自己把程序改坏了。

**Comment by jackandres** [comment]
![微信图片_20220122021349](https://user-images.githubusercontent.com/35865845/150579026-ae63df3e-f6df-4cdf-8a75-093fa9acaa0e.png)
![微信图片_20220122021408](https://user-images.githubusercontent.com/35865845/150579045-93f0dbb8-dce5-465e-a9b1-7ad8adba1898.png)
你好，大哥，想麻烦请教一下，在模拟盘是可以正常使用的，可是把Key.py换成正式实操盘，就提示不支持当前环境；有偿咨询，谢谢！！！

**Comment by Aureliano90** [comment]
Client test参数不是True还报错，只能说明你把模拟盘的API key用到了实盘。

**Comment by jackandres** [comment]
可以正常执行了，是我的问题，client.py里面的test需要修改成false才可以，这样才是正常实盘的开单；
![image](https://user-images.githubusercontent.com/35865845/150633610-cd7a0678-3fbe-4229-8120-7e14b6345b23.png)
就是还有一个小问题，就是我开单的是三个仓位，可是在资产里面为什么只显示两个，
![image](https://user-images.githubusercontent.com/35865845/150633808-6e766e7e-4b9d-4501-a999-b1a382fa8251.png)
![image](https://user-images.githubusercontent.com/35865845/150633824-1ecbdfe0-5887-4d66-934d-62ca63536e18.png)

**Comment by Aureliano90** [comment]
这种问题你自己研究吧，不是代码的bug不用问我。
