### ISSUE TITLE
新版本执行后异常报错

### ISSUE THREAD

**Issue by jackandres** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#3]
![image](https://user-images.githubusercontent.com/35865845/151032373-8ac07738-5653-4759-90e7-18517928d1da.png)
大佬，用你昨天刚刚迭代的版本执行后，报非法IP，但是用的还是同一个VPS，所以想请教一下，是我那个地方还需要调整的吗？麻烦帮忙看一下。谢谢！！！
![image](https://user-images.githubusercontent.com/35865845/151032768-87e6e912-e150-44a4-a98e-51e7c81415da.png)

**Comment by Aureliano90** [comment]
把okx.com域名换回okex.com试试。他们自己更新域名，可能内部都没准备好。

**Comment by jackandres** [comment]
![image](https://user-images.githubusercontent.com/35865845/151170319-fe104b24-e2df-4f52-be06-b8d8040ac0c1.png)
大佬，点击记录行情的时候，还是会报这个异常，这个是什么问题，在之前那个版本的时候都已经正常了。。。。

**Comment by Aureliano90** [comment]
先把httpx换回0.18.2吧。
