### ISSUE TITLE
Monitoring existing position give this warning

### ISSUE THREAD

**Issue by panpansh** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#6]
So, on debian using virtualenv with python 3.9 when I try to use monitor. (demo account)
Regards.

```
1
Crypto    Current  Predicted
SOL     -0.016%    -0.001%
SOL    Today's APR: -11.34%, 7 day APR: -1.62%, overall APR: -1211.42%
SOL    Today's APY: -10.72%, 7 day APY: -1.61%, overall APY: -100.00%
menu.py:36: RuntimeWarning: coroutine 'run_with_cancel.<locals>.wrapper.<locals>._coro' was never awaited
  mon.watch()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
menu.py:36: RuntimeWarning: coroutine 'Monitor.watch' was never awaited
  mon.watch()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I'm not sure I really understand the principle. does he manage on his own? I need to close my positions manually, right?
I need to use screen to fetch/monitor ? thanks

**Comment by Aureliano90** [comment]
Thanks for reporting. This is really an exotic issue. It comes down to how `multiprocessing` create child processes in different OS. In Linux the child processes are forked from the main one, so is the event loop.

Once it works, the program will manage your position on its own, assuming it is already hedged.

**Comment by panpansh** [comment]
thank you for your precise answer. so it doesn't block anything in theory or doesn't miss anything by not expecting it? how do I really know if I'm not going to wait forever? :)

**Comment by Aureliano90** [comment]
You have to elaborate your question. Or just use the latest commit.

**Comment by panpansh** [comment]
I didn't even pay attention! you're too stealthy it kills I'm going to test it then thank you <3

**Comment by panpansh** [comment]
```

**Comment by panpansh** [comment]
Hey what is the problem about fetch_records_lock variable access please ? (I dont know python by default). This one is in order to avoid starting another record_ticker process ? maybe I dont how it is managed.

Then what do you think to start it as service with sys.argv[1] == '--service' ?

do we agree that in this way I could issue orders from another python instance and everything will happen on its own ?
what is the strategy path please ?

```python
def main_menu(accountid: int):
    """主菜单

    :param accountid: 账号id
    """
    fetch_records_lock = False           # ?
    try:
        assert isinstance(accountid, int)
        fprint(f'{accountid=}')
        Monitor = monitor.Monitor(coin='BTC', accountid=accountid)
        loop = asyncio.get_event_loop()
        loop.run_until_complete(gather(Monitor.check_account_level(), Monitor.check_position_mode()))
        def fetch_records():
            if fetch_records_lock:           # ?
                record_process = multiprocessing.Process(target=record.record_ticker)
                record_process.start()
                record_process.join(0.2)
                fetch_records_lock = True           # ?
            else:
                print('fetch ticker already started')
        if len(sys.argv) > 1 and sys.argv[1] == '--service':
                fetch_records()
        else:
            while (command := input(main_menu_text)) != 'q':
                if command == '1':
                    monitor_all(accountid)
                elif command == '2':
                    crypto_menu(accountid)
                elif command == '3':
                    funding_menu(accountid)
                elif command == '4':
                    account_menu(accountid)
                elif command == '5':
                    fetch_records()
                elif command == 'q':
                    break
                else:
                    print(wrong_command)
    finally:
        if 'process' in locals():
            process.kill()
        trading_data.Stat.clean()
        monitor.Monitor.clean()
```

**Comment by Aureliano90** [comment]
You can add the service yourself. As long as a Python interpreter is recording, others use the same database. I don't know what you mean by strategy path.

**Comment by panpansh** [comment]
I have to take the time to understand I will start with that especially 🙏

**Comment by panpansh** [comment]
when I start the monitor process on windows, I cant "Input q to abort" with the last update. I have to Ctrl+C to exit.

```
Process Process-1:
Process Process-2:
Traceback (most recent call last):
Traceback (most recent call last):
```

**Comment by Aureliano90** [comment]
The child processes don't receive stdin.

**Comment by panpansh** [comment]
can you help me to send "self" here please ?
https://github.com/panpansh/Futures-Spot-Arbitrage-OKEx-V5/blob/main/menu.py#L222

do you have a discord or something like that ?

**Comment by Aureliano90** [comment]
What do you mean by "send self"?

It's just checking account settings.
