### ISSUE TITLE
关于数据库的问题

### ISSUE THREAD

**Issue by jifengthu** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#7]
当初始化程序的时候，按下监控现有仓位这个功能时候，数据库里没有数据，会报一个数据库为空的错误，请问这个问题应该怎么解决呢

**Comment by jifengthu** [comment]
![image](https://user-images.githubusercontent.com/61082374/163156747-19a38821-9bae-4249-8e71-b58fba69b8ef.png)

**Comment by Aureliano90** [comment]
数据库又没有你建仓的记录。

**Comment by Aureliano90** [comment]
@jifengthu 试下最新commit，可以导入原有仓位。
