### ISSUE TITLE
looking fine

### ISSUE THREAD

**Issue by dropcunt** [Aureliano90/Futures-Spot-Arbitrage-OKEx-V5#8]
Hi there,
I'm going through your code checking a little bit the concept. 
Out of the box i get this error:

`    async def get_crypto(accountid: int) -> tuple[str, Monitor]:
TypeError: 'type' object is not subscriptable`

Do you know what could be wrong here?

**Comment by Aureliano90** [comment]
Simply remove the type annotation.
